name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.24'
        cache: true

    - name: Get dependencies
      run: go mod download

    - name: Verify formatting
      run: |
        if [ "$(gofmt -l . | wc -l)" -gt 0 ]; then
          gofmt -d .
          echo "Code is not formatted with gofmt"
          exit 1
        fi

    - name: Run vet
      run: go vet ./...

    - name: Run tests
      run: go test -v ./...
