name: Makasero Issue Comment
on:
  issue_comment:
    types:
      - created

permissions:
  issues: write # Needed to allow gh to post comments

jobs:
  build_and_run_makasero: # Consolidated job name
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, '/makasero')
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.x'
          cache: true
      - name: Build makasero CLI
        run: |
          echo "Starting Go build..."
          cd cmd/makasero
          # Build and place the binary in a known location
          go build -v -o $GITHUB_WORKSPACE/makasero_binary || true
          cd -
          echo "Go build finished."
      - name: Install claude code
        id: install_claude_code
        run: make install-claude-code
      - name: Get issue contents
        id: get_issue_contents
        run: |
          ISSUE_CONTENTS=$(gh issue view ${{ github.event.issue.number }} --json body,comments --jq '{body: .body, comments: .comments | map({body: .body, author: .author.login, created_at: .createdAt})}'
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$ISSUE_CONTENTS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Run makasero
        id: run_makasero
        run: |
          echo "Running command: $GITHUB_WORKSPACE/makasero_binary -f issue_contents.txt"
          echo "${{ steps.get_issue.outputs.body }}" > issue_contents.txt
          # Execute the binary from the known location
          echo "Makasero output (stdout and stderr combined):"
          $GITHUB_WORKSPACE/makasero_binary "$(cat issue_contents.txt)"
          MAKASERO_OUTPUT=$($GITHUB_WORKSPACE/makasero_binary "$(cat issue_contents.txt)" 2>&1)
          echo "output<<EOF" >> $GITHUB_OUTPUT
          echo "$MAKASERO_OUTPUT" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      - name: Post comment to issue
        id: post_comment
        run: |
          gh issue comment ${{ github.event.issue.number }} --body "makasero Output: ${{ steps.run_makasero.outputs.output }}"
        env:
          GH_TOKEN: ${{ github.token }}
