name: Test LLM Integration

on:
  workflow_dispatch:
    inputs:
      test_prompt:
        description: 'Test prompt for LLM'
        default: 'Hello, AI. Please call the complete function.'
        required: false
      branch:
        description: 'Branch/commit to test (leave empty for current)'
        required: false
        
  issues:
    types: [labeled]
    
  pull_request:
    types: [labeled]
    
  issue_comment:
    types: [created]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  test-llm:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    if: |
      (github.event_name == 'workflow_dispatch') ||
      (github.event_name == 'issues' && github.event.label.name == 'test-llm') ||
      (github.event_name == 'pull_request' && github.event.label.name == 'test-llm') ||
      (github.event_name == 'issue_comment' && contains(github.event.comment.body, '/test-llm'))
      
    steps:
      - name: Extract custom prompt from comment
        if: github.event_name == 'issue_comment'
        id: extract_prompt
        run: |
          comment="${{ github.event.comment.body }}"
          if [[ "$comment" =~ /test-llm[[:space:]]+(.+) ]]; then
            echo "custom_prompt=${BASH_REMATCH[1]}" >> $GITHUB_OUTPUT
          else
            echo "custom_prompt=Hello, AI. Please call the complete function." >> $GITHUB_OUTPUT
          fi
          
      - name: Determine branch to checkout
        id: branch
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "issue_comment" && "${{ github.event.issue.pull_request }}" != "" ]]; then
            echo "branch=refs/pull/${{ github.event.issue.number }}/head" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.branch }}" != "" ]]; then
            echo "branch=${{ inputs.branch }}" >> $GITHUB_OUTPUT
          else
            echo "branch=${{ github.ref }}" >> $GITHUB_OUTPUT
          fi
          
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.branch.outputs.branch }}
          
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          cache: true
          
      - name: Get dependencies
        run: go mod download
          
      - name: Build makasero
        run: |
          cd cmd/makasero
          go build -v -o $GITHUB_WORKSPACE/makasero_binary
          cd -
          
      - name: Test basic LLM interaction
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          if [[ "${{ github.event_name }}" == "issue_comment" ]]; then
            TEST_PROMPT="${{ steps.extract_prompt.outputs.custom_prompt }}"
          elif [[ "${{ inputs.test_prompt }}" != "" ]]; then
            TEST_PROMPT="${{ inputs.test_prompt }}"
          else
            TEST_PROMPT="Hello, AI. Please call the complete function."
          fi
          
          echo "Testing with prompt: $TEST_PROMPT"
          
          echo "=== Test 1: Basic Interaction ==="
          timeout 60s $GITHUB_WORKSPACE/makasero_binary -config test-config.json "$TEST_PROMPT" || echo "Test 1 completed"
          
          echo "=== Test 2: Function Calling ==="
          timeout 60s $GITHUB_WORKSPACE/makasero_binary -config test-config.json "Please call the complete function with status 'success' and message 'Function calling works!'" || echo "Test 2 completed"
          
          echo "=== Test 3: Session Persistence ==="
          timeout 60s $GITHUB_WORKSPACE/makasero_binary -config test-config.json -s test_session "Create a new session and save it." || echo "Test 3 completed"
          
          echo "All LLM integration tests completed successfully!"
          
      - name: Comment test results on issue/PR
        if: github.event_name != 'workflow_dispatch'
        uses: actions/github-script@v7
        with:
          script: |
            const issueNumber = context.issue?.number || context.payload.pull_request?.number;
            if (issueNumber) {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: issueNumber,
                body: `✅ LLM Integration Test Completed
                
                **Branch**: \`${{ steps.branch.outputs.branch }}\`
                **Commit**: \`${{ github.sha }}\`
                **Tests**: Basic interaction, Function calling, Session persistence
                
                All tests completed successfully! ✨`
              });
            }
